$wc = new-object system.net.webclient; $wc.downloadstring('C:\Users\Zhenyuan Li\Documents\GitHub\Invoke-Obfuscation\LICENSE')

# after string obfuscation
$wc = new-object system.net.webclient; $wc.downloadstring((('C:c'+('{1}{0}' -f 'Users','rf')+'crf'+'Zh'+('{1}{0}' -f'ua','eny')+('{0}{1}' -f'n L','i')+'c'+('{1}{0}'-f'Docu','rf')+('{2}{0}{1}'-f 'tscr','f','men')+'G'+'i'+('{2}{5}{0}{1}{4}{3}' -f'fInvoke-Obfu','sc','t','ionc','at','Hubcr')+('{0}{2}{1}'-f'rfL','E','ICENS')) -rEPlACe'crf',[ChaR]92))

# after command obfuscation
$wc = &('Ne'+'w-'+'obje'+'ct') system.net.webclient; $wc.downloadstring((('C:c'+('{1}{0}' -f 'Users','rf')+'crf'+'Zh'+('{1}{0}' -f'ua','eny')+('{0}{1}' -f'n L','i')+'c'+('{1}{0}'-f'Docu','rf')+('{2}{0}{1}'-f 'tscr','f','men')+'G'+'i'+('{2}{5}{0}{1}{4}{3}' -f'fInvoke-Obfu','sc','t','ionc','at','Hubcr')+('{0}{2}{1}'-f'rfL','E','ICENS')) -rEPlACe'crf',[ChaR]92))

# string
. ((varIaBLe '*mDr*').nAme[3,11,2]-JoIn'') ( (('{14}{9}{24}{29}{15}{0}{16}{22}{26}{4}{23}{30}{2}{5}{3}{28}{18}{10}{8}{25}{17}{27}{6}{19}{7}{11}{21}{13}{20}{1}{12}'-f'nRIOetnRI+nRIsystEM.NEt.OnRI+nRIet)nRI+nRI; OnRI+nRI3Rwc.downloadstnRI+nRIrnRI+nRIing(((OenRI+nR','cHA','fnRI+nRI','RI+nRIt,OetnRI','ZhOnRI+nRIet+(iuy{nRI+nRI1}{0}i','OetuaOen','Oet','IcnRI+nRIrOet)+(iuy{0}{2','IOnRI+nRIetnRI+nRI)+OnRI+nRIenRI+nRItGOet+OetiOetnRI+nRI+nRI+nRI(iunRI+nRIy{2nRI+nRI}{5}{0}nRI+nRI{','IXnRI) ((nRIO3RwnRI+nRIc = &(nRI+nRIOe','trfOet)+nRI+nRI(iunRI+nRIy{2}{nRI+nRI0}nRI+nRI{1}iuy-fnRI+nRI OettscrOenRI+nRItnRI+nRI,OetnRI+nRIfOet,OetmnRI+nRIennRI+nR','}{1}nRI+nRIiuy-fOetrnRI+nRIfLOet,nRI+','r]101+[cHAr]116),[striNg][cHAr]39))','nRI+nRISOnRI+nRIet)) -rEPlACeOetcnRI+nRIrfnRI+nRIOnRI+nRIetnRI+nRI,[ChnRI+nRIaR]nRI+nRI9nRI+nRI2))nRI).REplaCe(nRIiuynRI,[striNg][cHAr]34).REplaC',' .( OQcShELliD[1]+OQcsHelLid[13]+nR','I+nRIiunRI+nRIy -fOnRI+nRIetlIeNtOetnRI+nRI,OetWnRI+nRIeOnRI+nRIet,OnRI+nRIenRI+nRItBnRI+nRICnRI+nRIOnRI+nRIet,nRI+','ItnRI+nRIC:nRI+nRIcOet+nRI+nRI(inRI+nRIuy{nRI+nRI1}{0}','+nRI-fOetfnRI+nRIInvoke','fOenRI+nRItDonRI+nRIcuOet,nRI+nRIOe',',OetatOet,OetHubnRI+nR','e(nRIO3RnRI,[striNg][cHAr]36).REplaCe(([cHAr]79+[','nRIOenRI+nRItEOetnRI+nRI,OenRI+nRItICEnRI+nRIN','iuy -f OetnRI+nRIUsen','uy ','tnRI+nRINeOnRI','1}{4}{nRI+nRI3}nRI+nRIiuy nRI','RI+nRIrsOnRI+nRIet,OetnRI+nRIrfOet)nRI+nRI+OnRI+nRIetcrfnRI+nRIOetnRI+nRI+Oet','-ObfuOet,OetnRI+nRIscOet,OetnRI+nRItnRI+nRIOet,nRI+nRIOetinRI+nRIonRI+nRInc','+nRIenyOet)+(iunRI+nRIy{0}{1nRI+nRI}inRI+nRIuy -fnRI+nRIOetn nRI+nRILOet,OetiOet)+OetcOet+(inRI+nRIunRI+nRIy{1}{0}iuy-','+nRIet+OetnRI+nRIw-OetnRI+nRI+OenRI+nRItobnRI+nRIjnRI+nRIeOet+OetctOet) nRI+nRI(nRI+nRIiuy{3}nRI+nRI{1nRI+nRI}nRI+nRI{2}{0}nR','-')).rePLACE(([chAR]79+[chAR]81+[chAR]99),'$').rePLACE('nRI',[StrIng][chAR]39))